### ISSUE TITLE
TODO 11-11-23

### ISSUE THREAD

**Issue by Daniele-Tentoni** [lucagiorgettismp/SemanticWebAttendance#5]
Happy Singles' Day!

Tento
- [x] Aggiornare grafici
    - aggiungere proprieta' di Person
    - aggiungere seminari
- [x] nota a piè pagina
- [x] mettere hasClassStudent nella Class e hasStudent e hasManualStudent in Attendable

Luca
- [ ] Rifare schema di massima
- [ ] Cambiare le attendance, correggere remote
- [ ] Mettere gli studenti nelle lezioni e nelle query
